# Generated by Django 2.2.4 on 2019-09-13 13:48

import MiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35)),
                ('Imagen', models.FileField(blank=True, upload_to=MiApp.models.subir_imagen)),
                ('sonido', models.FileField(upload_to='')),
            ],
        ),
    ]
