# Generated by Django 2.2.4 on 2019-09-19 13:03

import MiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='Imagen',
            field=models.FileField(blank=True, null=True, upload_to=MiApp.models.subir_imagen),
        ),
    ]
