# Generated by Django 2.2.4 on 2019-09-25 18:14

import MiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_auto_20190919_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='sonido',
            field=models.FileField(blank=True, null=True, upload_to=MiApp.models.subir_sonido),
        ),
    ]
